export interface ProjectDetail {
  label: string;
  text: string;
}

export interface ProjectLink {
  label: string;
  href: string;
}

export interface PersonalProject {
  name: string;
  tagline: string;
  status: string;
  summary: string;
  // Extra labelled lines shown between the summary and "Built"
  details?: ProjectDetail[];
  built?: string;
  next?: string;
  links: ProjectLink[];
}

// Each new personal project is one new entry here.
export const personalProjects: PersonalProject[] = [
  {
    name: "Mnemosyne",
    tagline: "Personal long-term memory system",
    status: "Currently building",
    summary:
      "A voice-first system for remembering. Spoken notes are transcribed, stored and retrieved on request. Every memory records where and when it came from, and memories that fall out of use drop to lower activation tiers instead of being deleted. Designed to adapt as models change rather than depend on any one of them.",
    built:
      "The inference backend, a Qwen model served with vLLM on a RunPod serverless endpoint.",
    next: "The memory layer and a mobile client in Expo.",
    links: [],
  },
  {
    name: "ARBITER",
    tagline: "A benchmark for vision-language models",
    status: "Currently building",
    summary:
      "Tests how well vision-language models read images, starting with charts. Tasks are generated by code, so the correct answer is known exactly rather than judged by an annotator. Difficulty changes one factor at a time (tick density, colour similarity, gridline strength, decimal precision), and a search finds the level at which each model starts to fail. The evaluation runner contains no language model.",
    details: [
      {
        label: "Why synthetic data",
        text: "Medical labels vary between annotators and cannot be shared publicly, so they cannot validate a measuring instrument.",
      },
      {
        label: "Models",
        text: "Qwen3-VL 4B and 8B, Gemma 3 4B, InternVL3.5 8B, MiniCPM-V 4.5.",
      },
    ],
    next: "Public release as a pip package, a Hugging Face dataset and a live demo.",
    links: [],
  },
  {
    name: "Mente Gris",
    tagline: "Offline habit tracker for Android",
    status: "Completed",
    summary:
      "A habit-tracking app with levels, streaks and reminders that runs entirely on the device. Access is protected by biometric login or a salted, hashed PIN, and the release build has no network permission.",
    built:
      "Expo and strict TypeScript; type checks, unit tests and the production bundle pass.",
    links: [],
  },
];
